CC=gcc
CFLAGS=-Wall -g -lm
all: default

default:
	$(CC) $(CFLAGS) example3.3.c -o example3.3
	$(CC) $(CFLAGS) example3.4.c -o example3.4
	$(CC) $(CFLAGS) example3.5.c -o example3.5
	$(CC) $(CFLAGS) example3.6.c -o example3.6
	$(CC) $(CFLAGS) exe3.1.c -o exe3.1
	$(CC) $(CFLAGS) exe3.2.c -o exe3.2
	$(CC) $(CFLAGS) exe3.3.c -o exe3.3
clean:
	rm -f a.out
	rm -f example3.3
	rm -f example3.4
	rm -f example3.5
	rm -f example3.6
	rm -f exe3.1
	rm -f exe3.2
	rm -f exe3.3
